import { type Currency, type Prestige, type Producer, type Upgrade } from "./models/base";
import type { GameRules } from "./rules";

/** Timing of one tick stage, aggregated over the ticks run so far. */
export interface StageMetrics {
  count: number;
  totalMs: number;
  avgMs: number;
  minMs: number;
  maxMs: number;
  lastMs: number;
}

/** Outcome of the bootstrap validation the engine runs on its first tick. */
export interface BootstrapReport {
  producers: number;
  currencies: number;
  upgrades: number;
  prestiges: number;
  pathsCompiled: number;
  validationErrors: string[];
  validationWarnings: string[];
  timeMs: number;
}

/** Engine-owned counters: tick timing, stage metrics, validation, overflow. */
export interface EngineStats {
  avgTime: number;
  minTime: number;
  maxTime: number;
  totalTime: number;
  ticks: number;
  lastTicks: number[];
  movingAvgTime: number;
  fastSkippedFrames: number;
  slowSkippedFrames: number;
  lastCallTimes: [string, number][];
  stageMetrics: Record<string, StageMetrics>;
  bootstrapReport?: BootstrapReport;
  validationErrors: string[];
  validationWarnings: string[];
  /** Overflow generated by the saturation rules on the last tick, per second. */
  overflowPerSec: number;
  /** The same overflow split by producer code. Empty without saturation. */
  overflowByProducer: Record<string, number>;
}

/**
 * Everything the engine reads and writes. Plain data: numbers are raw
 * `Numerus` records, so the state can be stored, cloned and serialized as is.
 * Hosts may extend it with their own fields; the engine never touches them.
 */
export interface GameState {
  stats: EngineStats;
  lastTick: number | undefined;
  producers: Producer[];
  upgrades: Upgrade[];
  currencies: Currency[];
  prestiges: Prestige[];
  /** Optional data-driven mechanics. Absent means producers, upgrades and prestiges only. */
  rules?: GameRules;
}

/** An empty state: zeroed stats, no entities, no rules. */
export const createInitialState = (): GameState => ({
  stats: {
    avgTime: 0,
    minTime: Infinity,
    maxTime: 0,
    totalTime: 0,
    ticks: 0,
    lastTicks: [],
    movingAvgTime: 0,
    fastSkippedFrames: 0,
    slowSkippedFrames: 0,
    lastCallTimes: [],
    stageMetrics: {},
    validationErrors: [],
    validationWarnings: [],
    overflowPerSec: 0,
    overflowByProducer: {},
  },
  lastTick: undefined,
  producers: [],
  currencies: [],
  prestiges: [],
  upgrades: [],
});
